# Docker Architecture & Production Containers — lesson m03l06 — Multi Stage Builds, Targets And Build Secrets
# https://learnsome.tech/courses/docker-course/watch?lesson=m03l06
# © LearnSome.tech
FROM python:3.12-alpine
WORKDIR /app
COPY app.py .
CMD ["python", "app.py"]
