# Docker Architecture & Production Containers — lesson m03l01 — Build Context, Dockerignore And Your First Dockerfile
# https://learnsome.tech/courses/docker-course/watch?lesson=m03l01
# © LearnSome.tech
FROM python:3.12-alpine
WORKDIR /app
COPY app.py .
CMD ["python", "app.py"]
