# Docker Architecture & Production Containers — lesson m03l05 — CMD, ENTRYPOINT, USER And Process Signals
# https://learnsome.tech/courses/docker-course/watch?lesson=m03l05
# © LearnSome.tech
FROM python:3.12-alpine
WORKDIR /app
COPY app.py .
CMD ["python", "app.py"]
