# Docker Architecture & Production Containers — lesson m03l02 — FROM, WORKDIR, COPY And ADD
# https://learnsome.tech/courses/docker-course/watch?lesson=m03l02
# © LearnSome.tech
FROM python:3.12-alpine
WORKDIR /app
COPY app.py .
CMD ["python", "app.py"]
