# Docker Architecture & Production Containers — lesson m01l03 — Union Filesystems, Images And Writable Layers
# https://learnsome.tech/courses/docker-course/watch?lesson=m01l03
# © LearnSome.tech
FROM alpine:3.20
RUN mkdir /app
COPY note.txt /app/note.txt
CMD ["cat", "/app/note.txt"]
