# Docker Architecture & Production Containers — lesson m03l04 — ARG, ENV, LABEL, EXPOSE And VOLUME
# https://learnsome.tech/courses/docker-course/watch?lesson=m03l04
# © LearnSome.tech
FROM python:3.12-alpine
WORKDIR /app
COPY app.py .
CMD ["python", "app.py"]
